version: '2'

services:
    vnc:
        hostname: vnc
        build: .
#        image: dorowu/ubuntu-desktop-lxde-vnc:latest
        environment:
            USER: ${BASIC_USER}
#            VNC_PASSWORD: ${BASIC_PASSWORD}
            HTTP_PASSWORD: ${BASIC_PASSWORD}
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - home:/home
        networks:
            - default
    files:
        hostname: files
        image: filebrowser/filebrowser:v1.10.0
        # Uncoment for debug purposes
        # ports:
        #     - 6082:80
        command: --no-auth --baseurl=/files
        volumes:
            - home:/srv
        networks:
            - default

volumes:
    home:

networks:
    default:
